import fs from "fs";
import path from "path";
import { MedusaContainer } from "@medusajs/framework";
import { ContainerRegistrationKeys } from "@medusajs/framework/utils";
import { updateProductsWorkflow } from "@medusajs/medusa/core-flows";

/**
 * Replaces each Printful product's images with the multi-view mockups
 * generated by scripts/generate_mockups.py (front, back, angle shots).
 *
 * Printful's sync API only exposes a single front-view mockup per variant, so
 * back prints were invisible on product pages. The Mockup Generator API can
 * render every placement, but returns temporary S3 URLs — the Python script
 * re-hosts them in the public assets repo and writes a manifest that this
 * script consumes.
 *
 *   MOCKUP_MANIFEST=/path/to/mockups.json \
 *     npx medusa exec ./src/scripts/apply-printful-mockups.ts
 */
export default async function applyPrintfulMockups({
  container,
}: {
  container: MedusaContainer;
}) {
  const logger = container.resolve(ContainerRegistrationKeys.LOGGER);
  const query = container.resolve(ContainerRegistrationKeys.QUERY);

  // `railway run` does not reliably forward ad-hoc env vars into the command
  // it spawns, so the checked-in manifest is the dependable source; the env
  // var only overrides it when explicitly set and present.
  const candidates = [
    process.env.MOCKUP_MANIFEST,
    path.resolve(process.cwd(), "mockups.json"),
    path.resolve(__dirname, "../../mockups.json"),
    path.resolve(process.cwd(), "apps/backend/mockups.json"),
  ].filter(Boolean) as string[];

  const manifestPath = candidates.find((p) => fs.existsSync(p));
  if (!manifestPath) {
    logger.error(
      `No manifest found. Looked in:\n  ${candidates.join("\n  ")}\nRun scripts/generate-printful-mockups.py first.`
    );
    return;
  }
  logger.info(`Using manifest: ${manifestPath}`);

  const manifest: Record<string, { name: string; images: string[] }> =
    JSON.parse(fs.readFileSync(manifestPath, "utf8"));

  const entries = Object.entries(manifest).filter(
    ([, v]) => v.images && v.images.length
  );
  if (!entries.length) {
    logger.warn("Manifest has no products with images.");
    return;
  }

  const { data: products } = await query.graph({
    entity: "product",
    fields: ["id", "title", "metadata"],
  });
  // Keyed on the Printful id from metadata, not the handle: handles are
  // name-derived slugs and change whenever a product is renamed.
  const byPrintfulId = new Map(
    products
      .filter((p) => (p.metadata as any)?.printful_product_id)
      .map((p) => [String((p.metadata as any).printful_product_id), p])
  );

  let updated = 0;
  for (const [printfulId, { name, images }] of entries) {
    const product = byPrintfulId.get(String(printfulId));
    if (!product) {
      logger.warn(`  skipped ${name}: no store product for Printful id ${printfulId}`);
      continue;
    }

    try {
      await updateProductsWorkflow(container).run({
        input: {
          selector: { id: product.id },
          update: {
            thumbnail: images[0],
            images: images.map((url) => ({ url })),
          },
        },
      });
      logger.info(`  ✓ ${name} — ${images.length} image(s)`);
      updated++;
    } catch (e: any) {
      logger.error(`  ✗ ${name}: ${e.message}`);
    }
  }

  logger.info(`Done. ${updated}/${entries.length} product(s) updated.`);
}
